apiVersion: apps/v1
kind: Deployment
metadata:
  name: okard-frontend
spec:
  template:
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: okard-frontend
          image: ghcr.io/o-kard/okard-frontend:latest