apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

namePrefix: uat-
namespace: uat

# This setting patches the base deployment specifically for UAT
patches:
  - target:
      kind: Deployment
      name: okard-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 2
  - path: deployment-patch.yaml

images:
  - name: okard-frontend
    newTag: latest
    