apiVersion: apps/v1
kind: Deployment
metadata:
  name: okard-frontend
  labels:
    app: okard-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okard-frontend
  template:
    metadata:
      labels:
        app: okard-frontend
    spec:
      containers:
        - name: okard-frontend
          image: ghcr.io/o-kard/okard-frontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: okard-frontend-secrets
