// import type { Metadata } from "next";
// import {
//   ClerkProvider,
//   SignInButton,
//   SignUpButton,
//   SignedIn,
//   SignedOut,
//   UserButton,
// } from "@clerk/nextjs";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Clerk Next.js Quickstart",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <ClerkProvider>
//       <html lang="en">
//         <body
//           className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//         >
//           <header className="flex justify-end items-center p-4 gap-4 h-16">
//             <SignedOut>
//               <SignInButton />
//               <SignUpButton>
//                 <button className="bg-[#6c47ff] text-white rounded-full font-medium text-sm sm:text-base h-10 sm:h-12 px-4 sm:px-5 cursor-pointer">
//                   Sign Up
//                 </button>
//               </SignUpButton>
//             </SignedOut>
//             <SignedIn>
//               <UserButton />
//             </SignedIn>
//           </header>
//           {children}
//         </body>
//       </html>
//     </ClerkProvider>
//   );
// }
import type { Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import ThemeRegistry from "../modules/themeRegister/ThemeRegistry";
import AppShell from "../modules/layout/AppShell";
import ProfileGatekeeper from "../components/common/ProfileGatekeeper";

//import font
import { Syncopate, Montserrat } from "next/font/google";

const syncopate = Syncopate({
  weight: ["400", "700"],
  subsets: ["latin"],
  variable: "--font-syncopate",
  display: "swap",
});

const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Okard",
  description: "Fund your next big idea",
  icons: {
    icon: "/Logo_sun_bg.svg",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider
      appearance={{
        variables: {
          colorPrimary: "#12C998",
          colorBackground: "#ffffff",
          colorText: "#222222",
          colorInputBackground: "#ffffff",
          colorInputText: "#222222",
          colorTextSecondary: "#666666",
          borderRadius: "16px",
        },
        elements: {
          cardBox: {
            boxShadow: "0 4px 20px rgba(0, 0, 0, 0.1)",
            borderRadius: "16px",
            backgroundColor: "#ffffff",
          },
          headerTitle: {
            fontWeight: "bold",
          },
          formFieldInput: {
            borderRadius: "16px",
            borderColor: "rgba(0, 0, 0, 0.23)",
            "&:hover": {
              borderColor: "#222222",
            },
            "&:focus": {
              borderColor: "#12C998",
              boxShadow: "0 0 0 1px #12C998",
            },
          },
          formButtonPrimary: {
            fontWeight: "bold",
            padding: "12px 16px",
            textTransform: "none",
            backgroundColor: "#12C998",
            color: "#ffffff",
            "&:hover": {
              backgroundColor: "#0ea880",
            },
          },
          footerActionLink: {
            color: "#12C998",
            fontWeight: "bold",
            "&:hover": {
              color: "#0ea880",
            },
          },
        },
      }}
    >
      <html lang="en">
        <body className={`${syncopate.variable} ${montserrat.variable}`}>
          <ThemeRegistry>
            <ProfileGatekeeper>
              <AppShell>{children}</AppShell>
            </ProfileGatekeeper>
          </ThemeRegistry>
        </body>
      </html>
    </ClerkProvider>
  );
}
