apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: okard-frontend-prd
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: okard-frontend=ghcr.io/o-kard/okard-frontend
    argocd-image-updater.argoproj.io/okard-frontend.update-strategy: latest
    argocd-image-updater.argoproj.io/okard-frontend.allow-tags: regexp:^prd-.*$
    argocd-image-updater.argoproj.io/write-back-method: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/o-kard/okard-frontend.git'
    targetRevision: main
    path: k3s/overlays/prd
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true